baseURL = "https://rkirov.github.io/"
languageCode = "en-us"
title = "Rado's Blog"
theme = "fuji"

pygmentsCodeFences = true

disqusShortname = "" #Disqus shortname
googleAnalytics = "" #Google Analytics ID

[author]
    name = "Rado Kirov"           #Author name
    github = "rkirov"         #Github username
    twitter = "radokirov"        #Twitter username

[params]
    tagline = "subtly different semantics"
    customCSS = []  #Optional Customised CSS
