baseURL = "https://rkirov.github.io/"
languageCode = "en-us"
title = "Subtly Different Semantics"
theme = "fuji"

pygmentsCodeFences = true

disqusShortname = "" #Disqus shortname
googleAnalytics = "" #Google Analytics ID

[author]
    name = "Rado Kirov"           #Author name
    github = "rkirov"         #Github username
    twitter = "radokirov"        #Twitter username

[params]
    tagline = "subtly different semantics"
    customCSS = []  #Optional Customised CSS

    license = "Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License (CC BY-NC-SA 4.0)"
    licenseLink = "http://creativecommons.org/licenses/by-nc-sa/4.0/"

[menu]
  [[menu.nav]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.link]]
    name = "GitHub"
    url = "https://github.com/rkirov"
  [[menu.link]]
    name = "Twitter"
    url = "https://twitter.com/radokirov"
