baseURL = "https://rkirov.github.io/"
languageCode = "en-us"
title = "Rado's Radical Reflections"
theme = "hugo-bearblog"

pygmentsCodeFences = true

# Generate "Bearblog"-like URLs !only!, see https://bearblog.dev/.
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
[permalinks]
  blog = "/:slug/"
  tags = "/posts/:slug"

[params]
    license = "Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License (CC BY-NC-SA 4.0)"
    licenseLink = "http://creativecommons.org/licenses/by-nc-sa/4.0/"

[params.author]
    author = "Rado Kirov"     #Author name
    email = "rkirov@gmail.com" #Email address

[params.social]
    github = "rkirov"         #Github username
    twitter = "radokirov"     #Twitter username

[[menu.main]]
  name = "Blog"
  url = "/posts/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2